### ISSUE TITLE
LSP?

### ISSUE THREAD

**Issue by alphapapa** [Fuco1/Elsa#77]
Crazy idea that I just thought of: would ELSA make sense as a foundation for an Elisp LSP server?  I can imagine using eglot with an elisp LSP server built on ELSA.  Of course, since ELSA runs in Emacs, maybe that would be silly.  But on the other hand, it would cleanly abstract ELSA into an external process which eglot could interact with asynchronously, preserving UI responsiveness.

Just an idea.  :)

**Comment by Fuco1** [comment]
Yea, also see #17 .  Emacs has lots of webservers so running it separately is no problem I think.  In fact using your editing instance for LSP backend would be quite crazy as reloading or redefining functions would break everything immediately.  That's why I also advocate running Elsa via Cask right now to have a separate clean environment.
